package pojo;
// Generated Dec 15, 2017 12:20:35 AM by Hibernate Tools 4.3.1



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer idStatus;
     private String statusName;

    public Status() {
    }

    public Status(String statusName) {
       this.statusName = statusName;
    }
   
    public Integer getIdStatus() {
        return this.idStatus;
    }
    
    public void setIdStatus(Integer idStatus) {
        this.idStatus = idStatus;
    }
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }




}


